const express = require('express');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const speakeasy = require('speakeasy');
const qrcode = require('qrcode');
const rateLimit = require('express-rate-limit');
const helmet = require('helmet');
const https = require('https');
const http = require('http');
const os = require('os');

// --- CONFIG FILE ---
// Settings live in a .env file next to the app so `npm start` just works, with no
// environment juggling. Real environment variables still win, so a systemd unit or a
// one-off `PORT=1234 npm start` can override it.
(function loadDotEnv() {
    try {
        const file = require('path').join(__dirname, '.env');
        if (!require('fs').existsSync(file)) return;
        for (const raw of require('fs').readFileSync(file, 'utf8').split('\n')) {
            const line = raw.trim();
            if (!line || line.startsWith('#')) continue;
            const eq = line.indexOf('=');
            if (eq < 1) continue;
            const key = line.slice(0, eq).trim();
            let val = line.slice(eq + 1).trim();
            if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
                val = val.slice(1, -1);
            }
            if (process.env[key] === undefined) process.env[key] = val;
        }
    } catch (e) { /* a malformed .env must not stop the server booting */ }
})();

const { log, getLogs, clearLogs, encrypt, decrypt, captureConsole, getAuditLog } = require('./utils');
const { checkAccountLock, recordFailure, recordSuccess, lockStats, parseCookies, newCsrfToken, safeEqual, hashToken } = require('./security');
captureConsole(); // mirror library console.error/warn into the dashboard log
const { getUsers, saveUsers, getAllAccounts, getAccount, saveAccount, deleteAccountFile, getSessions, saveSessions, getBundles, saveBundles, getSettings, saveSettings, getGlobalProxies, saveGlobalProxies } = require('./data');
const { startBotProcess, stopBot, getActiveBots, getGameName, searchGames, sendDiscordWebhook, getGamePayload, updateBotGames, requestFreeGames, queueFreeGames, flushDirtyAccounts, refreshOwnedApps } = require('./bot');

// 245 Steam clients share this process. A throw from any one of their callbacks
// would otherwise take down every other bot, so log and keep serving. This is a
// backstop -- the teardown path in bot.js is what stops clients throwing at all.
process.on('uncaughtException', (err) => {
    log(`Uncaught exception: ${err && err.stack ? err.stack : err}`, "ERROR");
});
process.on('unhandledRejection', (reason) => {
    log(`Unhandled rejection: ${reason && reason.stack ? reason.stack : reason}`, "ERROR");
});

const app = express();
const server = http.createServer(app);
const { Server } = require("socket.io");
const io = new Server(server);

let serverPublicIp = "Loading...";
https.get('https://api.ipify.org', (res) => {
    let data = ''; res.on('data', c => data += c);
    res.on('end', () => { if(data) serverPublicIp = data.trim(); });
}).on('error', () => { serverPublicIp = "Server IP"; });

// Only trust X-Forwarded-For when actually behind a reverse proxy. Trusting it
// unconditionally lets any client spoof its IP and walk straight past the login
// rate limiter. Set TRUST_PROXY=1 (or a hop count) when running behind nginx.
app.set('trust proxy', process.env.TRUST_PROXY ? Number(process.env.TRUST_PROXY) || 1 : false);
app.use(helmet({
    contentSecurityPolicy: {
        directives: {
            defaultSrc: ["'self'"],
            // No inline <script> blocks exist, so 'unsafe-inline' is not needed here.
            // Dropping it means an injected <script> tag cannot execute at all.
            scriptSrc: ["'self'", "https://cdn.jsdelivr.net"],
            // Inline on*= handlers are generated by dashboard.js; see the delegated
            // dispatcher there. Tightened to 'none' once those were removed.
            scriptSrcAttr: ["'none'"],
            objectSrc: ["'none'"],
            baseUri: ["'self'"],
            frameAncestors: ["'self'"],
            formAction: ["'self'"],
            styleSrc: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdnjs.cloudflare.com"],
            fontSrc: ["'self'", "https://fonts.gstatic.com", "https://cdnjs.cloudflare.com"],
            imgSrc: ["'self'", "data:", "https://avatars.steamstatic.com", "https://raw.githubusercontent.com", "https://cdn.cloudflare.steamstatic.com", "https://shared.akamai.steamstatic.com", "https://steamcdn-a.akamaihd.net"],
            connectSrc: ["'self'", "https://raw.githubusercontent.com"], // For fetching game list
            upgradeInsecureRequests: [],
        },
    },
    crossOriginEmbedderPolicy: false
}));
app.use(express.json({ limit: '10mb' }));
app.use(express.static('public'));

// --- SOCKET.IO ---
// Previously any client that could reach the port could connect and receive every
// log line, including account names and Steam errors. Sockets now authenticate with
// the same session cookie as the REST API, and are placed in rooms so a non-admin
// only ever receives events about accounts they own.
const { setLogListener } = require('./utils');

io.use((socket, next) => {
    try {
        const cookies = parseCookies({ headers: socket.handshake.headers || {} });
        const token = cookies[SESSION_COOKIE] || (socket.handshake.auth && socket.handshake.auth.token);
        const sessions = getSessions();
        const sess = token ? sessions[hashToken(token)] : null;
        if (!sess || sess.expiresAt <= Date.now()) return next(new Error('unauthorized'));
        socket.data.user = { username: sess.username, role: sess.role };
        next();
    } catch (e) { next(new Error('unauthorized')); }
});

// Who is currently connected, so the push loop knows which payloads to build.
// Every user gets their own room -- two admins can own different accounts, so they
// cannot share one payload.
const liveUsers = new Map(); // username -> { role, sockets }

io.on('connection', (socket) => {
    const u = socket.data.user;
    socket.join(`user:${u.username}`);
    if (u.role === 'admin') socket.join('admins');

    const rec = liveUsers.get(u.username) || { role: u.role, sockets: 0 };
    rec.role = u.role; rec.sockets++;
    liveUsers.set(u.username, rec);

    // Full snapshot so a fresh tab isn't blank until the next tick; deltas follow.
    const snapshot = accountsPayloadFor(u);
    socket.emit('accounts', snapshot);
    // Seed the baseline so the next tick diffs against what this tab actually has.
    const seed = new Map();
    snapshot.forEach(a => seed.set(a.username, JSON.stringify(a)));
    lastPushed.set(u.username, seed);

    socket.on('disconnect', () => {
        const r = liveUsers.get(u.username);
        if (!r) return;
        r.sockets--;
        if (r.sockets <= 0) { liveUsers.delete(u.username); lastPushed.delete(u.username); }
    });
});

setLogListener((logEntry) => {
    // Admins see everything; everyone else only lines tagged with an account of theirs.
    io.to('admins').emit('new_log', logEntry);
    if (logEntry.relatedUser) {
        const acc = getAccount(logEntry.relatedUser);
        if (acc && acc.owner) io.to(`user:${acc.owner}`).emit('new_log', logEntry);
    }
});

// With 'trust proxy' off, express-rate-limit keys on the real TCP peer address and
// ignores X-Forwarded-For -- which is exactly what we want, since an untrusted client
// could otherwise spoof that header for a fresh bucket per request. Turn off the
// warning that fires when a client sends the header anyway; our handling is deliberate.
const RL_VALIDATE = { xForwardedForHeader: false };
const loginLimiter = rateLimit({ windowMs: 15*60*1000, max: 10, message: { success: false, msg: "Too many attempts" }, validate: RL_VALIDATE });
const bulkLimiter = rateLimit({ windowMs: 60*1000, max: 5, message: { success: false, msg: "Too many bulk requests" }, validate: RL_VALIDATE });
// Blunt session-token guessing. Generous enough for the dashboard's own polling.
const apiLimiter = rateLimit({ windowMs: 60*1000, max: 600, message: { error: 'Too many requests' }, validate: RL_VALIDATE });

// Surface the situation once instead of throwing a stack trace per request.
let warnedForwarded = false;
app.use((req, res, next) => {
    if (!warnedForwarded && req.headers['x-forwarded-for'] && app.get('trust proxy') === false) {
        warnedForwarded = true;
        log(`Requests carry X-Forwarded-For but TRUST_PROXY is not set, so rate limits key on the direct peer (${req.socket.remoteAddress}). If a reverse proxy really is in front, start with TRUST_PROXY=1.`, "WARN");
    }
    next();
});

// --- INIT BOTS ---
// Steam rate-limits logins per IP, so pacing only needs to be per IP. The old code
// staggered every account by 5s globally, which took 20 minutes for 245 accounts while
// doing nothing extra for safety. Group by proxy and pace within each group instead:
// accounts on different IPs start in parallel, accounts sharing one IP still queue.
const autoStartAccounts = getAllAccounts().filter(acc => acc.autoStart);
const PER_IP_STAGGER_MS = 5000;
const CROWDED_IP_WARN = 20;

const byIp = new Map();
autoStartAccounts.forEach(acc => {
    const key = (acc.proxy || '').trim() || '__server_ip__';
    if (!byIp.has(key)) byIp.set(key, []);
    byIp.get(key).push(acc);
});

let longestQueueMs = 0;
byIp.forEach((group, key) => {
    group.forEach((acc, i) => {
        // A small jitter keeps separate groups from landing in lockstep.
        const delay = 2000 + (i * PER_IP_STAGGER_MS) + Math.floor(Math.random() * 1500);
        longestQueueMs = Math.max(longestQueueMs, delay);
        setTimeout(() => startBotProcess(acc), delay);
    });
    if (group.length >= CROWDED_IP_WARN) {
        const where = key === '__server_ip__' ? 'the server IP (no proxy)' : 'one proxy';
        log(`${group.length} auto-start accounts share ${where}. Steam rate-limits per IP, so spread them across more proxies.`, "WARN");
    }
});

if (autoStartAccounts.length) {
    log(`Auto-starting ${autoStartAccounts.length} accounts across ${byIp.size} IP(s); last one begins in ~${Math.round(longestQueueMs / 60000)} min.`, "SYSTEM");
}

// --- SESSION COOKIES ---
// The token lives in an httpOnly cookie so page scripts can't read it: an XSS bug
// can then act as the user while the page is open, but can't exfiltrate a token that
// works for the next 7 days. Secure is set when the request arrived over HTTPS
// (behind nginx that means trusting X-Forwarded-Proto, hence TRUST_PROXY).
const SESSION_COOKIE = 'bb_session';
const CSRF_COOKIE = 'bb_csrf';

function isSecureRequest(req) { return req.secure || req.headers['x-forwarded-proto'] === 'https'; }

function setSessionCookies(req, res, token, csrf, remember) {
    const secure = isSecureRequest(req) ? '; Secure' : '';
    // Lax rather than Strict: Strict drops the cookie when arriving from an external
    // link, which logs the user out for no security gain here (all mutations are POST
    // and additionally CSRF-checked).
    const base = `Path=/; SameSite=Lax${secure}`;
    const age = remember ? `; Max-Age=${7 * 24 * 3600}` : '';
    res.append('Set-Cookie', `${SESSION_COOKIE}=${token}; HttpOnly; ${base}${age}`);
    // Readable by JS on purpose: the page echoes it back in a header (double submit).
    res.append('Set-Cookie', `${CSRF_COOKIE}=${csrf}; ${base}${age}`);
}

function clearSessionCookies(req, res) {
    const secure = isSecureRequest(req) ? '; Secure' : '';
    res.append('Set-Cookie', `${SESSION_COOKIE}=; HttpOnly; Path=/; SameSite=Lax${secure}; Max-Age=0`);
    res.append('Set-Cookie', `${CSRF_COOKIE}=; Path=/; SameSite=Lax${secure}; Max-Age=0`);
}

function sessionTokenFrom(req) {
    // Cookie first; the Authorization header stays supported for scripts and curl.
    const c = parseCookies(req);
    return c[SESSION_COOKIE] || req.headers.authorization || null;
}

const requireAuth = (req, res, next) => {
    const token = sessionTokenFrom(req);
    const sessions = getSessions();
    // Sessions are keyed by the token's hash; the raw token exists only in the cookie.
    const key = token ? hashToken(token) : null;
    const sess = key ? sessions[key] : null;

    if (!sess || sess.expiresAt <= Date.now()) {
        // Only touch disk when a real session actually expired. Previously every
        // request with a bad or absent token triggered a synchronous full rewrite of
        // sessions.json, which is a free disk-write amplifier for an unauthenticated
        // caller.
        if (key && sessions[key]) { delete sessions[key]; saveSessions(sessions); }
        clearSessionCookies(req, res);
        return res.status(401).json({ error: 'Unauthorized' });
    }

    // CSRF: only cookie-authenticated state-changing requests need it. A caller using
    // an explicit Authorization header already proves it can read the token, which a
    // cross-site attacker cannot do.
    const usedCookie = !!parseCookies(req)[SESSION_COOKIE];
    const mutating = !['GET', 'HEAD', 'OPTIONS'].includes(req.method);
    if (usedCookie && mutating) {
        const sent = req.headers['x-csrf-token'];
        if (!sent || !safeEqual(String(sent), sess.csrf || '')) {
            return res.status(403).json({ error: 'Bad CSRF token' });
        }
    }

    req.user = sess;
    req.sessionToken = token;
    req.sessionKey = key;
    next();
};

// One-time migration: sessions written before tokens were hashed are keyed by the raw
// token, which is both unusable now and a live credential sitting on disk. A raw token
// and a SHA-256 are both 64 hex chars so they can't be told apart -- drop the lot and
// have everyone sign in once more.
(function migrateSessions() {
    const sessions = getSessions();
    const stale = Object.keys(sessions).filter(k => sessions[k] && sessions[k].v !== 2);
    if (!stale.length) return;
    stale.forEach(k => delete sessions[k]);
    saveSessions(sessions);
    log(`Cleared ${stale.length} pre-hash session(s); those users must sign in again.`, "SYSTEM");
})();

// Expired sessions used to be pruned only as a side effect of a failed request.
setInterval(() => { saveSessions(getSessions()); }, 60 * 60 * 1000).unref();

app.get('/api/verify_session', (req, res) => {
    const token = sessionTokenFrom(req);
    const sessions = getSessions();
    const key = token ? hashToken(token) : null;
    const sess = key ? sessions[key] : null;
    if (sess && sess.expiresAt > Date.now()) {
        // The panel user may have been deleted while this session was still valid.
        const user = getUsers().find(u => u.username === sess.username);
        if (!user) return res.json({ success: false });
        // Re-issue the CSRF cookie so a browser holding an older copy converges instead
        // of failing every state-changing request until it is reloaded.
        const secure = isSecureRequest(req) ? '; Secure' : '';
        res.append('Set-Cookie', `${CSRF_COOKIE}=${sess.csrf}; Path=/; SameSite=Lax${secure}`);
        res.json({ success: true, role: sess.role, username: sess.username, has2FA: !!user.twoFactorSecret, csrf: sess.csrf });
    } else res.json({ success: false });
});

// A bcrypt hash of a value nobody can supply, so the "no such user" path costs the
// same as a wrong password and can't be used to enumerate usernames by timing.
const DUMMY_HASH = bcrypt.hashSync(crypto.randomBytes(32).toString('hex'), 12);

app.post('/api/login', loginLimiter, async (req, res) => {
    const { username, password, token } = req.body;
    if (typeof username !== 'string' || typeof password !== 'string') return res.status(400).json({ success: false, msg: 'Invalid Credentials' });
    // Per-account lock, checked before any password work. The IP limiter above only
    // stops one address; this is what stops a botnet grinding a single account.
    const lock = checkAccountLock(username);
    if (lock.locked) {
        log(`Login blocked for "${String(username).slice(0, 32)}" (locked ${lock.retryAfterSec}s) from ${req.ip}`, "AUTH");
        res.set('Retry-After', String(lock.retryAfterSec));
        return res.status(429).json({ success: false, msg: `Too many failed attempts. Try again in ${Math.ceil(lock.retryAfterSec / 60)} min.` });
    }

    const user = getUsers().find(u => u.username === username);
    const ok = await bcrypt.compare(password, user ? user.password : DUMMY_HASH);
    if (!user || !ok) {
        const r = recordFailure(username);
        log(`Failed login for "${String(username).slice(0, 32)}" from ${req.ip}${r.lockedForSec ? ` - account locked ${r.lockedForSec}s after ${r.fails} failures` : ''}`, "AUTH");
        return res.status(401).json({ success: false, msg: 'Invalid Credentials' });
    }
    if (user.twoFactorSecret) {
        if (!token) return res.json({ success: false, requires2fa: true });
        if (!speakeasy.totp.verify({ secret: decrypt(user.twoFactorSecret), encoding: 'base32', token, window: 1 })) {
            // A wrong 2FA code counts as a failure too, or 2FA becomes a free oracle.
            const r = recordFailure(username);
            log(`Invalid 2FA for "${user.username}" from ${req.ip}${r.lockedForSec ? ` - locked ${r.lockedForSec}s` : ''}`, "AUTH");
            return res.status(401).json({ success: false, msg: 'Invalid Code' });
        }
    }
    recordSuccess(username);

    // Flag sign-ins from an address this account hasn't used before. Cheap signal, and
    // the first thing you want to know if credentials leak.
    const knownIps = Array.isArray(user.knownIps) ? user.knownIps : [];
    const ip = String(req.ip || '').slice(0, 45);
    if (ip && !knownIps.includes(ip)) {
        knownIps.push(ip);
        user.knownIps = knownIps.slice(-10);
        saveUsers(getUsers());
        if (knownIps.length > 1) {
            log(`New sign-in location for "${user.username}": ${ip}`, "SECURITY");
            sendDiscordWebhook("New Login Location", `Panel user **${user.username}** signed in from a new address: \`${ip}\``, 16776960);
        }
    }

    const st = crypto.randomBytes(32).toString('hex');
    const csrf = newCsrfToken();
    const sessions = getSessions();
    // Only the hash is persisted; st itself goes to the browser cookie and nowhere else.
    sessions[hashToken(st)] = { v: 2, username: user.username, role: user.role, csrf, expiresAt: Date.now() + (7*24*3600*1000) };
    saveSessions(sessions);
    setSessionCookies(req, res, st, csrf, !!req.body.remember);
    log(`${user.username} signed in from ${req.ip}`, "AUDIT");
    // The token is no longer returned: it lives in an httpOnly cookie. csrf is for
    // the double-submit header.
    res.json({ success: true, csrf, role: user.role, username: user.username, has2FA: !!user.twoFactorSecret });
});

app.post('/api/logout', (req, res) => {
    const token = sessionTokenFrom(req);
    const sessions = getSessions();
    const key = token ? hashToken(token) : null;
    if (key && sessions[key]) { delete sessions[key]; saveSessions(sessions); }
    clearSessionCookies(req, res);
    res.json({ success: true });
});

app.use('/api/', apiLimiter, requireAuth);

app.post('/api/library', (req, res) => { if(!verifyOwner(req, req.body.username)) return res.status(403).json({}); const acc = getAccount(req.body.username); if (!acc) return res.status(404).json({ games: [] }); res.json({ games: acc.ownedGames || [] }); });

// Force an immediate re-read of the account's owned games from Steam. The dashboard's
// "Refresh" button in Manage Games called this route, but it was never implemented on
// the server (a leftover from the abandoned src/ refactor), so the button always
// failed with a generic error.
app.post('/api/library/refresh', async (req, res) => {
    const username = req.body.username;
    if (!verifyOwner(req, username)) return res.status(403).json({ success: false, error: 'Not allowed' });
    const acc = getAccount(username);
    if (!acc) return res.status(404).json({ success: false, error: 'Account not found' });

    const bot = getActiveBots()[username];
    if (!bot || !bot.client || !bot.client.steamID) {
        // Steam only tells us the library over a logged-in session.
        return res.status(409).json({ success: false, error: 'Start the bot first - Steam only reports the library to a signed-in session.' });
    }

    try {
        const apps = await refreshOwnedApps(username, bot.client);
        if (!apps) return res.status(502).json({ success: false, error: 'Steam did not return the library. Try again in a moment.' });
        forgetAccountCaches(username);
        log(`${username}: library refreshed on request (${apps.length} games).`, "BOT", username);
        res.json({ success: true, count: apps.length });
    } catch (e) {
        res.status(500).json({ success: false, error: e.message || 'Refresh failed' });
    }
});

app.post('/api/accounts/bulk', bulkLimiter, (req, res) => {
    const { data, category, autoStart, autoAccept, bundle } = req.body;
    // `data` is a textarea paste; anything else (missing, null, an object) used to
    // throw on .split and 500.
    if (typeof data !== 'string' || !data.trim()) return res.status(400).json({ success: false, msg: 'Paste at least one account line.' });
    const lines = data.split(/\r?\n/); let c = 0; let skipped = 0;
    const bundles = getBundles(); 
    let selectedGames = [730];
    if (bundle === 'none') selectedGames = [];
    else if (bundle && bundles[bundle]) selectedGames = bundles[bundle];
    lines.forEach(l => { const p = l.trim().split(':'); if (p.length >= 2) { if (!getAccount(p[0].trim())) { saveAccount({ username: p[0].trim(), password: p[1].trim(), sharedSecret: p[2]?p[2].trim():"", proxy: p[3]?p[3].trim():"", category: category||"Default", autoStart: !!autoStart, autoAccept: !!autoAccept, games: selectedGames, nickname: null, owner: req.user.username, grandTotal: "0.0", addedAt: Date.now(), boostedHours: 0, personaState: 1 }); c++; } else { skipped++; } } });
    log(`${req.user.username} bulk-added ${c} accounts (${skipped} skipped).`, "AUDIT"); res.json({ success: true, count: c, skipped });
});
app.post('/api/accounts/export', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    // This hands over every password in plaintext, so require a fresh 2FA code from
    // an admin who has it enabled. One stolen session should not be enough.
    const me = getUsers().find(u => u.username === req.user.username);
    if (me && me.twoFactorSecret) {
        const code = String(req.body && req.body.token || '');
        if (!speakeasy.totp.verify({ secret: decrypt(me.twoFactorSecret), encoding: 'base32', token: code, window: 1 })) {
            log(`${req.user.username} failed 2FA on account export.`, "AUDIT");
            return res.status(401).json({ success: false, msg: 'Invalid 2FA code', requires2fa: true });
        }
    }
    const accounts = getAllAccounts();
    log(`${req.user.username} exported ${accounts.length} accounts.`, "AUDIT");
    const data = accounts.map(a => {
        let line = `${a.username}:${a.password}`;
        if (a.sharedSecret) line += `:${a.sharedSecret}`;
        if (a.proxy) line += `:${a.proxy}`;
        return line;
    }).join('\n');
    res.json({ success: true, data });
});
app.post('/api/accounts/bulk_update', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    const { updates, globalChanges } = req.body; 
    if (!Array.isArray(updates)) return res.status(400).json({});
    
    const bundles = getBundles();
    const activeBots = getActiveBots();
    let count = 0;

    updates.forEach(u => {
        const changes = { ...globalChanges, ...u };
        const acc = getAccount(changes.username);
        if (acc) {
            let proxyChanged = false;
            if (changes.proxy !== undefined && changes.proxy !== acc.proxy) {
                acc.proxy = changes.proxy;
                proxyChanged = true;
            }
            if (changes.category !== undefined) acc.category = changes.category;
            if (changes.autoStart !== undefined) acc.autoStart = changes.autoStart;
            if (changes.autoAccept !== undefined) acc.autoAccept = changes.autoAccept;
            if (changes.autoReclaim !== undefined) acc.autoReclaim = !!changes.autoReclaim;
            if (changes.scheduleEnabled !== undefined) acc.scheduleEnabled = !!changes.scheduleEnabled;
            if (changes.scheduleStart !== undefined) acc.scheduleStart = changes.scheduleStart;
            if (changes.scheduleEnd !== undefined) acc.scheduleEnd = changes.scheduleEnd;
            
            // Bulk Games (Bundle)
            if (changes.bundle) {
                if (changes.bundle === 'none') {
                    acc.games = [];
                    const bot = activeBots[acc.username];
                    if (bot && bot.client && bot.status === 'Running') updateBotGames(acc.username);
                } else if (bundles[changes.bundle]) {
                    acc.games = bundles[changes.bundle];
                    const bot = activeBots[acc.username];
                    if (bot && bot.client && bot.status === 'Running') updateBotGames(acc.username);
                }
            }

            saveAccount(acc);
            
            // Restart if proxy changed and bot is running
            if (proxyChanged) {
                const bot = activeBots[acc.username];
                if (bot && (bot.status === 'Running' || bot.status === 'Logging in...' || bot.status.includes('Rate Limit'))) {
                    stopBot(acc.username);
                    setTimeout(() => startBotProcess(acc), 1000);
                }
            }
            
            count++;
        }
    });
    res.json({ success: true, count });
});
app.post('/api/accounts', (req, res) => { if (getAccount(req.body.username)) return res.status(400).json({ error: 'Exists' }); saveAccount({ username: req.body.username, password: req.body.password, sharedSecret: req.body.sharedSecret, category: req.body.category||"Default", autoStart: req.body.autoStart, autoAccept: req.body.autoAccept, games: [730], nickname: null, owner: req.user.username, grandTotal: "0.0", addedAt: Date.now(), boostedHours: 0, personaState: 1 }); res.json({ success: true }); });
app.post('/api/edit', (req, res) => { 
    const { oldUsername, newUsername, newPassword, newSharedSecret, newProxy, newCategory, newAutoStart, newAutoAccept } = req.body;
    if(!verifyOwner(req, oldUsername)) return res.status(403).json({});
    const ex = getAccount(oldUsername);
    if (!ex) return res.status(404).json({ error: 'Not found' });
    stopBot(oldUsername);
    if (oldUsername !== newUsername) { deleteAccountFile(oldUsername); forgetAccountCaches(oldUsername); delete getActiveBots()[oldUsername]; }
    // Only overwrite what the caller actually sent. The edit modal omits proxy and
    // autoAccept entirely, so taking these unconditionally wiped the account's proxy
    // on every edit. Blank password/secret means "unchanged", as the UI advertises.
    saveAccount({
        ...ex,
        username: newUsername,
        password: (newPassword && newPassword !== "") ? newPassword : ex.password,
        sharedSecret: (newSharedSecret && newSharedSecret !== "") ? newSharedSecret : ex.sharedSecret,
        proxy: newProxy !== undefined ? newProxy : ex.proxy,
        category: newCategory || ex.category || "Default",
        autoStart: newAutoStart !== undefined ? newAutoStart : ex.autoStart,
        autoAccept: newAutoAccept !== undefined ? newAutoAccept : ex.autoAccept,
        autoReclaim: req.body.newAutoReclaim !== undefined ? !!req.body.newAutoReclaim : !!ex.autoReclaim,
        scheduleEnabled: req.body.newScheduleEnabled !== undefined ? !!req.body.newScheduleEnabled : !!ex.scheduleEnabled,
        scheduleStart: req.body.newScheduleStart !== undefined ? req.body.newScheduleStart : ex.scheduleStart,
        scheduleEnd: req.body.newScheduleEnd !== undefined ? req.body.newScheduleEnd : ex.scheduleEnd
    });
    res.json({ success: true });
});
// /api/accounts is polled by every open dashboard every few seconds and resolves a
// name for every game of every account. Cache the resolved list per account and
// reuse it until that account's games array is actually replaced.
const gameNameCache = new Map(); // username -> { ref, resolved }
function resolveGames(acc) {
    const ref = acc.games || [];
    const hit = gameNameCache.get(acc.username);
    if (hit && hit.ref === ref) return hit.resolved;
    const resolved = ref.map(id => ({ id, name: getGameName(id) }));
    gameNameCache.set(acc.username, { ref, resolved });
    return resolved;
}
// Kept off the account object itself: saveAccount() spreads the record to disk, so
// anything stashed there would be persisted into the account JSON.
const ownedIdCache = new Map(); // username -> { ref, ids }
function resolveOwnedIds(acc) {
    const ref = acc.ownedGames || [];
    const hit = ownedIdCache.get(acc.username);
    if (hit && hit.ref === ref) return hit.ids;
    const ids = ref.map(g => g.id);
    ownedIdCache.set(acc.username, { ref, ids });
    return ids;
}
function forgetAccountCaches(username) {
    gameNameCache.delete(username);
    ownedIdCache.delete(username);
}

// Shared by the REST route and the socket push loop so both always agree.
function accountsPayloadFor(user) {
    const accounts = getAllAccounts().filter(a => a.owner === user.username || (user.role === 'admin' && !a.owner));
    const activeBots = getActiveBots();
    return accounts.map(acc => {
        const b = activeBots[acc.username];
        let displayIp = serverPublicIp;
        if (acc.proxy) {
            try {
                if (acc.proxy.includes('@')) displayIp = acc.proxy.split('@')[1].split(':')[0];
                else if (acc.proxy.includes('://')) displayIp = acc.proxy.split('://')[1].split(':')[0];
                else displayIp = acc.proxy.split(':')[0];
            } catch(e) {}
        }
        return {
            username: acc.username, nickname: acc.nickname || acc.username, avatarHash: acc.avatarHash || null,
            status: b ? b.status : 'Stopped',
            lastError: b ? b.lastError : null,
            nextRotation: b ? b.nextRotation : null,
            nextRetry: b ? b.nextRetry || null : null,
            grandTotal: acc.grandTotal || "0.0", steamId: acc.steamId || null, games: resolveGames(acc),
            customStatus: acc.customStatus || "", addedAt: acc.addedAt || Date.now(), boostedHours: acc.boostedHours || 0,
            personaState: acc.personaState !== undefined ? acc.personaState : 1, category: acc.category || "Default",
            autoStart: !!acc.autoStart, autoAccept: !!acc.autoAccept, autoReclaim: !!acc.autoReclaim,
            scheduleEnabled: !!acc.scheduleEnabled, scheduleStart: acc.scheduleStart || '', scheduleEnd: acc.scheduleEnd || '',
            playBlocked: b ? !!b.playBlocked : false,
            vacBanned: !!acc.vacBanned, limited: !!acc.limited, locked: !!acc.locked,
            usingRefreshToken: b ? !!b.usingRefreshToken : !!acc.refreshToken,
            ip: displayIp,
            proxy: acc.proxy || "",
            ownedGames: resolveOwnedIds(acc),
            hasSharedSecret: !!acc.sharedSecret
        };
    });
}

app.get('/api/accounts', (req, res) => res.json(accountsPayloadFor(req.user)));

// --- LIVE PUSH ---
// The dashboard used to re-fetch every account every few seconds per open tab. Now
// the server builds each user's payload once per tick and pushes it only when it
// actually changed, so an idle panel costs nothing.
// Per-user snapshot of what each dashboard already has, so we can push only what
// changed. Sending the whole list every 3s was ~283 KB per tick at 245 accounts
// (~340 MB/hour per open tab) even when nothing moved -- painful over mobile data.
const lastPushed = new Map(); // username -> Map(account -> JSON of that account)

function diffAccounts(prev, next) {
    const changed = [];
    const seen = new Set();
    for (const acc of next) {
        seen.add(acc.username);
        const json = JSON.stringify(acc);
        if (prev.get(acc.username) !== json) { changed.push(acc); prev.set(acc.username, json); }
    }
    const removed = [];
    for (const name of prev.keys()) if (!seen.has(name)) { removed.push(name); prev.delete(name); }
    return { changed, removed };
}

setInterval(() => {
    if (liveUsers.size === 0) return;
    for (const [username, rec] of liveUsers) {
        let payload;
        try { payload = accountsPayloadFor({ username, role: rec.role }); }
        catch (e) { continue; }

        let prev = lastPushed.get(username);
        if (!prev) { prev = new Map(); lastPushed.set(username, prev); }

        const { changed, removed } = diffAccounts(prev, payload);
        if (!changed.length && !removed.length) continue; // nothing moved: send nothing
        io.to(`user:${username}`).emit('accounts_delta', { changed, removed });
    }
}, 3000).unref();
function verifyOwner(req, username) { if (req.user.role === 'admin') return true; const acc = getAccount(username); return acc && acc.owner === req.user.username; }
app.post('/api/start', (req, res) => {
    if (!verifyOwner(req, req.body.username)) return res.status(403).json({});
    const acc = getAccount(req.body.username);
    if (!acc) return res.status(404).json({ error: 'Account not found' });
    startBotProcess(acc);
    res.json({ success: true });
});
app.post('/api/stop', (req, res) => { if (!verifyOwner(req, req.body.username)) return res.status(403).json({}); stopBot(req.body.username); res.json({ success: true }); });
app.post('/api/restart', (req, res) => {
    if (!verifyOwner(req, req.body.username)) return res.status(403).json({});
    const username = req.body.username;
    if (!getAccount(username)) return res.status(404).json({ error: 'Account not found' });
    stopBot(username);
    // Re-read on the timer: the account could be deleted during the pause.
    setTimeout(() => { const acc = getAccount(username); if (acc) startBotProcess(acc); }, 1000);
    res.json({ success: true });
});
app.post('/api/steamguard', (req, res) => { if (!verifyOwner(req, req.body.username)) return res.status(403).json({}); const b = getActiveBots()[req.body.username]; if (b && b.guardCallback) { b.guardCallback(req.body.code); b.status = 'Verifying...'; b.guardCallback = null; res.json({ success: true }); } else res.status(400).json({}); });
app.post('/api/restart_all', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    const activeBots = getActiveBots();
    let count = 0;
    const botsToRestart = [];
    Object.keys(activeBots).forEach(u => {
        if (activeBots[u].status === 'Running' || activeBots[u].status === 'Logging in...' || activeBots[u].status.includes('Rate Limit')) {
            botsToRestart.push(u);
            stopBot(u);
            count++;
        }
    });
    
    const BATCH_SIZE = 5;
    let idx = 0;
    const runBatch = () => {
        const batch = botsToRestart.slice(idx, idx + BATCH_SIZE);
        if(batch.length === 0) return;
        batch.forEach(u => { const acc = getAccount(u); if (acc) startBotProcess(acc); });
        idx += BATCH_SIZE;
        if(idx < botsToRestart.length) setTimeout(runBatch, 2000);
    };
    setTimeout(runBatch, 1000);

    log(`Restart All triggered. Cycling ${count} bots (Threaded).`, "SYSTEM", req.user.username);
    res.json({ success: true, count });
});
app.post('/api/panic', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    const activeBots = getActiveBots();
    let count = 0;
    Object.keys(activeBots).forEach(u => {
        if (activeBots[u].status === 'Running' || activeBots[u].status === 'Logging in...') {
            stopBot(u);
            count++;
        }
    });
    log(`Panic Stop triggered. Stopped ${count} bots.`, "SYSTEM", req.user.username);
    res.json({ success: true, count });
});
app.post('/api/games', (req, res) => {
    if (!verifyOwner(req, req.body.username)) return res.status(403).json({});
    const acc = getAccount(req.body.username);
    // verifyOwner short-circuits to true for admins without checking existence, so an
    // unknown username reached this line and threw.
    if (!acc) return res.status(404).json({ error: 'Account not found' });
    acc.games = (req.body.games || []).filter(id => Number.isInteger(id) && id > 0 && id < 2147483647);
    acc.customStatus = req.body.customStatus || ""; acc.personaState = parseInt(req.body.personaState); 
    saveAccount(acc); 
    const b = getActiveBots()[req.body.username]; 
    if (b && b.client && b.status === 'Running') { updateBotGames(req.body.username); }
    res.json({ success: true }); 
});
app.post('/api/games/free_license', bulkLimiter, (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    const { usernames, games, autoStart } = req.body;
    if (!usernames || !Array.isArray(usernames) || !games || !Array.isArray(games)) return res.status(400).json({ error: 'Invalid data' });
    
    const activeBots = getActiveBots();
    const processList = [];

    usernames.forEach(u => {
        if (verifyOwner(req, u)) processList.push(u);
    });

    res.json({ success: true, count: processList.length, queued: processList.length, message: "Processing started in background" });

    (async () => {
        const BATCH_SIZE = 10;
        const total = processList.length;
        let processed = 0;
        let stats = { success: 0, owned: 0, failed: 0, queued: 0 };
        io.emit('free_games_progress', { processed: 0, total, stats });

        for (let i = 0; i < processList.length; i += BATCH_SIZE) {
            const batch = processList.slice(i, i + BATCH_SIZE);
            
            const promises = batch.map(u => {
                const bot = activeBots[u];
                let p;
                if (bot && bot.client && bot.status === 'Running') { 
                    p = requestFreeGames(u, games); 
                } else if (autoStart) { 
                    queueFreeGames(u, games, true); 
                    startBotProcess(getAccount(u)); 
                    p = Promise.resolve({ result: 'queued' });
                } else {
                    p = Promise.resolve({ result: 'error', msg: 'Offline' });
                }
                
                return p.then(r => {
                    if (r.result === 'success') stats.success++;
                    else if (r.result === 'owned') stats.owned++;
                    else if (r.result === 'error') stats.failed++;
                    else if (r.result === 'queued') stats.queued++;
                    processed++;
                    io.emit('free_games_progress', { processed, total, stats });
                    return r;
                });
            });

            await Promise.all(promises);
            if (i + BATCH_SIZE < processList.length) await new Promise(r => setTimeout(r, 10000));
        }
        io.emit('free_games_progress', { processed: total, total, stats, complete: true });
    })();
});
app.post('/api/delete', (req, res) => {
    if (!verifyOwner(req, req.body.username)) return res.status(403).json({});
    stopBot(req.body.username);
    deleteAccountFile(req.body.username);
    forgetAccountCaches(req.body.username);
    delete getActiveBots()[req.body.username];
    // Destructive and irreversible, so it belongs in the persistent audit trail.
    log(`${req.user.username} deleted account "${req.body.username}".`, "AUDIT");
    res.json({ success: true });
});
app.post('/api/get_account', (req, res) => { if(!verifyOwner(req, req.body.username)) return res.status(403).json({}); const acc = getAccount(req.body.username); if (!acc) return res.status(404).json({}); res.json({ username: acc.username, hasSharedSecret: !!acc.sharedSecret, proxy: acc.proxy || '', category: acc.category || '', autoStart: !!acc.autoStart, autoAccept: !!acc.autoAccept, autoReclaim: !!acc.autoReclaim, hasRefreshToken: !!acc.refreshToken, scheduleEnabled: !!acc.scheduleEnabled, scheduleStart: acc.scheduleStart || '', scheduleEnd: acc.scheduleEnd || '' }); });
app.post('/api/settings/password', async (req, res) => {
    const users = getUsers();
    const u = users.find(x => x.username === req.user.username);
    if (!u || typeof req.body.newPass !== 'string' || req.body.newPass.length < 8) return res.status(400).json({ msg: 'Password must be at least 8 characters' });
    if (!(await bcrypt.compare(req.body.currentPass, u.password))) return res.status(400).json({});
    u.password = await bcrypt.hash(req.body.newPass, 12);
    saveUsers(users);
    // Invalidate this user's other sessions; a password change should log out anyone
    // holding an older token. The caller keeps the session they are using.
    const sessions = getSessions();
    const keep = req.sessionKey;
    let revoked = 0;
    for (const t in sessions) { if (sessions[t].username === u.username && t !== keep) { delete sessions[t]; revoked++; } }
    saveSessions(sessions);
    log(`${u.username} changed password (revoked ${revoked} other session(s)).`, "AUDIT");
    res.json({ success: true });
});
app.post('/api/settings/2fa/generate', (req, res) => { const s = speakeasy.generateSecret({ name: `BruddiBooster (${req.user.username})` }); qrcode.toDataURL(s.otpauth_url, (e, d) => { res.json({ secret: s.base32, qr: d }); }); });
app.post('/api/settings/2fa/enable', (req, res) => { if (speakeasy.totp.verify({ secret: req.body.secret, encoding: 'base32', token: req.body.token })) { const users = getUsers(); users.find(u => u.username === req.user.username).twoFactorSecret = encrypt(req.body.secret); saveUsers(users); res.json({ success: true }); } else res.status(400).json({}); });
app.post('/api/settings/2fa/disable', (req, res) => { const users = getUsers(); users.find(u => u.username === req.user.username).twoFactorSecret = null; saveUsers(users); res.json({ success: true }); });
app.get('/api/logs', (req, res) => {
    let logs = getLogs();
    if (req.user.role !== 'admin') {
        const userAccounts = getAllAccounts().filter(a => a.owner === req.user.username).map(a => a.username);
        logs = logs.filter(l => l.relatedUser && userAccounts.includes(l.relatedUser));
    }
    // Objects, not bare strings, so the UI can filter by account.
    res.json(logs.map(l => ({ text: l.text, relatedUser: l.relatedUser || null })));
});
// Security events that survive a restart: logins, failed logins, lockouts, credential
// exports, account and user deletions. Deliberately admin-only and not clearable from
// the UI -- an audit trail an attacker can wipe is not an audit trail.
app.get('/api/audit', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json([]);
    res.json(getAuditLog(300));
});

app.post('/api/logs/clear', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    clearLogs();
    res.json({ success: true });
});
app.get('/api/search_games', (req, res) => { const q = (req.query.q || "").toLowerCase().trim(); if (!q) return res.json([]); res.json(searchGames(q)); });
app.get('/api/users', (req, res) => { if (req.user.role !== 'admin') return res.status(403).json([]); res.json(getUsers().map(u => ({ username: u.username, role: u.role }))); });
app.post('/api/users', async (req, res) => { if (req.user.role !== 'admin') return res.status(403).json({}); const users = getUsers(); users.push({ username: req.body.username, password: await bcrypt.hash(req.body.password, 12), role: 'user' }); saveUsers(users); res.json({ success: true }); });
app.post('/api/users/delete', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    if (req.body.username === req.user.username) return res.status(400).json({ msg: 'Cannot delete yourself' });
    let users = getUsers();
    users = users.filter(u => u.username !== req.body.username);
    saveUsers(users);
    // Their live sessions must die with the account.
    const sessions = getSessions();
    for (const t in sessions) if (sessions[t].username === req.body.username) delete sessions[t];
    saveSessions(sessions);
    log(`${req.user.username} deleted panel user "${req.body.username}".`, "AUDIT");
    res.json({ success: true });
});

app.get('/api/bundles', (req, res) => {
    const b = getBundles();
    const resolved = {};
    for (const [k, v] of Object.entries(b)) {
        resolved[k] = v.map(id => ({ id, name: getGameName(id) }));
    }
    res.json(resolved);
});
// Bundles are global, so writing them is admin-only (reading them is not).
app.post('/api/bundles', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    const { name, games } = req.body;
    if (!name || !games || !Array.isArray(games)) return res.status(400).json({ error: 'Invalid data' });
    const b = getBundles(); b[name] = games.filter(id => Number.isInteger(id) && id > 0 && id < 2147483647); saveBundles(b); res.json({ success: true });
});
app.post('/api/bundles/delete', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    const { name } = req.body;
    const b = getBundles(); if (b[name]) { delete b[name]; saveBundles(b); } res.json({ success: true });
});

// --- SYSTEM / MEMORY ---
// v8.getHeapStatistics().heap_size_limit is what actually kills the process, so
// report usage against that rather than against total system RAM.
const v8 = require('v8');
app.get('/api/system', (req, res) => {
    const mu = process.memoryUsage();
    const limit = v8.getHeapStatistics().heap_size_limit;
    const bots = getActiveBots();
    res.json({
        rssMB: +(mu.rss / 1048576).toFixed(1),
        heapUsedMB: +(mu.heapUsed / 1048576).toFixed(1),
        heapLimitMB: +(limit / 1048576).toFixed(1),
        heapPct: +((mu.heapUsed / limit) * 100).toFixed(1),
        externalMB: +(mu.external / 1048576).toFixed(1),
        systemTotalMB: +(os.totalmem() / 1048576).toFixed(0),
        systemFreeMB: +(os.freemem() / 1048576).toFixed(0),
        uptimeSec: Math.floor(process.uptime()),
        runningBots: Object.keys(bots).filter(u => bots[u].client).length,
        totalAccounts: getAllAccounts().length,
        nodeVersion: process.version
    });
});

// Daily playtime datapoints for the statistics view.
app.post('/api/history', (req, res) => {
    const names = Array.isArray(req.body.usernames) ? req.body.usernames : null;
    const mine = getAllAccounts().filter(a => a.owner === req.user.username || (req.user.role === 'admin' && !a.owner));
    const wanted = names ? mine.filter(a => names.includes(a.username)) : mine;

    // Merge per-account series into one daily total, which is what the chart shows.
    const totals = new Map();
    wanted.forEach(a => (a.history || []).forEach(p => totals.set(p.d, (totals.get(p.d) || 0) + p.h)));
    const series = [...totals.entries()].sort((x, y) => x[0] < y[0] ? -1 : 1).map(([d, h]) => ({ date: d, hours: +h.toFixed(1) }));

    res.json({
        series,
        perAccount: wanted.map(a => ({ username: a.username, history: a.history || [] }))
    });
});

// --- BACKUP / RESTORE ---
// Everything needed to rebuild the panel except credentials, so the file is safe to
// keep off-box. Passwords, shared secrets and refresh tokens are deliberately excluded.
app.get('/api/backup', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    const backup = {
        version: 1,
        createdAt: new Date().toISOString(),
        settings: getSettings(),
        bundles: getBundles(),
        globalProxies: getGlobalProxies(),
        accounts: getAllAccounts().map(a => ({
            username: a.username, category: a.category, games: a.games || [],
            customStatus: a.customStatus || '', personaState: a.personaState,
            autoStart: !!a.autoStart, autoAccept: !!a.autoAccept, autoReclaim: !!a.autoReclaim,
            scheduleEnabled: !!a.scheduleEnabled, scheduleStart: a.scheduleStart || '', scheduleEnd: a.scheduleEnd || '',
            proxy: a.proxy || '', owner: a.owner || null, addedAt: a.addedAt,
            boostedHours: a.boostedHours || 0, baselineHours: a.baselineHours,
            history: a.history || []
        }))
    };
    log(`${req.user.username} downloaded a config backup (${backup.accounts.length} accounts).`, "AUDIT");
    res.json(backup);
});

app.post('/api/restore', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    const b = req.body && req.body.backup;
    if (!b || b.version !== 1 || !Array.isArray(b.accounts)) return res.status(400).json({ error: 'Not a valid backup file' });

    if (b.settings) saveSettings(b.settings);
    if (b.bundles) saveBundles(b.bundles);
    if (Array.isArray(b.globalProxies)) saveGlobalProxies(b.globalProxies);

    // Settings are merged onto existing accounts; credentials are never touched, and
    // accounts that no longer exist are reported rather than silently recreated
    // (we have no password for them).
    let updated = 0; const missing = [];
    b.accounts.forEach(rec => {
        const acc = getAccount(rec.username);
        if (!acc) { missing.push(rec.username); return; }
        Object.assign(acc, {
            category: rec.category, games: rec.games || [], customStatus: rec.customStatus || '',
            personaState: rec.personaState, autoStart: !!rec.autoStart, autoAccept: !!rec.autoAccept,
            autoReclaim: !!rec.autoReclaim, scheduleEnabled: !!rec.scheduleEnabled,
            scheduleStart: rec.scheduleStart || '', scheduleEnd: rec.scheduleEnd || '',
            proxy: rec.proxy || ''
        });
        if (Array.isArray(rec.history) && rec.history.length) acc.history = rec.history;
        saveAccount(acc);
        forgetAccountCaches(rec.username);
        updated++;
    });
    log(`${req.user.username} restored config: ${updated} accounts updated, ${missing.length} not found.`, "AUDIT");
    res.json({ success: true, updated, missing });
});

app.get('/api/settings', (req, res) => { res.json(getSettings()); });
app.post('/api/settings', (req, res) => { 
    if (req.user.role !== 'admin') return res.status(403).json({});
    const s = getSettings(); 
    s.discordWebhook = req.body.discordWebhook; 
    s.rotationInterval = req.body.rotationInterval;
    saveSettings(s); 
    res.json({ success: true }); 
});
app.get('/api/proxies/global', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json([]);
    res.json(getGlobalProxies());
});
app.post('/api/proxies/global', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    const { proxies } = req.body;
    if (!Array.isArray(proxies)) return res.status(400).json({});
    saveGlobalProxies(proxies);
    res.json({ success: true });
});
app.post('/api/settings/test_webhook', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    sendDiscordWebhook("Test Notification", "This is a test message from BruddiBooster.", 5814783, req.body.discordWebhook);
    res.json({ success: true });
});
app.post('/api/proxy/check', (req, res) => {
    if (req.user.role !== 'admin') return res.status(403).json({});
    const { proxy } = req.body;
    if (!proxy) return res.json({ success: false, msg: "No proxy provided" });

    try {
        const u = new URL(proxy);
        if (!u.hostname || !u.port) throw new Error("Invalid Proxy");
        
        const options = {
            host: u.hostname,
            port: u.port,
            method: 'GET',
            path: 'http://api.steampowered.com/ISteamDirectory/GetCMList/v1/?cellid=0',
            headers: { 'Host': 'api.steampowered.com' },
            timeout: 5000
        };
        
        if (u.username) {
            options.headers['Proxy-Authorization'] = 'Basic ' + Buffer.from(u.username + ':' + u.password).toString('base64');
        }

        let responded = false;
        const safeReply = (data) => {
            if (responded) return;
            responded = true;
            res.json(data);
        };

        const request = http.request(options, (response) => {
            response.resume(); // Consume the stream either way, or the socket is held open
            if (response.statusCode === 200) {
                safeReply({ success: true, ip: "Steam Reachable" });
            } else {
                safeReply({ success: false, msg: `HTTP ${response.statusCode}` });
            }
        });

        request.on('error', (err) => safeReply({ success: false, msg: "Connection Failed" }));
        request.on('timeout', () => { request.destroy(); safeReply({ success: false, msg: "Timeout" }); });
        request.end();
    } catch (e) {
        res.json({ success: false, msg: "Invalid Format" });
    }
});

// Failing to bind is fatal -- without this the uncaughtException handler above
// would swallow EADDRINUSE and leave a process running that never serves anything.
// The first run creates admin/password. Nag until that is changed.
(async () => {
    const admin = getUsers().find(u => u.username === 'admin');
    if (admin && await bcrypt.compare('password', admin.password)) {
        log('SECURITY: the default admin password is still in use. Change it in Settings.', "WARN");
    }
})();

server.on('error', (err) => {
    log(`Server error: ${err.message}`, "ERROR");
    process.exit(1);
});
const PORT = Number(process.env.PORT) || 3000;
// Behind nginx, bind to loopback so the panel isn't reachable directly on :3000 --
// otherwise anyone can bypass the proxy's TLS and rate limiting. Defaults to all
// interfaces so existing setups are unchanged.
const HOST = process.env.HOST || '0.0.0.0';
server.listen(PORT, HOST, () => {
    const limitMB = Math.round(v8.getHeapStatistics().heap_size_limit / 1048576);
    log(`BruddiBooster v18 Running on ${HOST}:${PORT} (heap limit ${limitMB} MB, Node ${process.version})`, "SYSTEM");
    if (HOST === '0.0.0.0' && process.env.TRUST_PROXY) {
        // Loopback is only the right answer when the proxy runs on this same machine;
        // suggesting it blindly breaks setups where the proxy is another host.
        log(`Listening on all interfaces, so port ${PORT} is reachable directly and bypasses the proxy. If your proxy is on this machine, set HOST=127.0.0.1 in .env; if it is another machine, firewall the port to it instead.`, "WARN");
    }
    if (limitMB < 2500) log(`Heap limit is ${limitMB} MB. Start via "npm start" (or add --max-old-space-size=3072) for more headroom.`, "WARN");
});

// --- MEMORY WATCHDOG ---
// The process died with "heap out of memory" before this existed, with no warning in
// the logs. Warn while there is still headroom to act.
let lastMemWarn = 0;
setInterval(() => {
    const used = process.memoryUsage().heapUsed;
    const limit = v8.getHeapStatistics().heap_size_limit;
    const pct = (used / limit) * 100;
    if (pct > 85 && Date.now() - lastMemWarn > 5 * 60 * 1000) {
        lastMemWarn = Date.now();
        const msg = `Heap at ${pct.toFixed(0)}% of limit (${(used/1048576).toFixed(0)}/${(limit/1048576).toFixed(0)} MB)`;
        log(msg, "WARN");
        sendDiscordWebhook("High Memory Usage", msg, 16776960);
    }
}, 60 * 1000).unref();

// --- GRACEFUL SHUTDOWN ---
// Without this, a restart drops every Steam connection mid-session and loses up to
// STATS_FLUSH_MINUTES of accumulated boostedHours.
let shuttingDown = false;
function shutdown(signal) {
    if (shuttingDown) return;
    shuttingDown = true;
    log(`Received ${signal}. Shutting down...`, "SYSTEM");

    const bots = getActiveBots();
    const running = Object.keys(bots).filter(u => bots[u].client);
    running.forEach(u => stopBot(u));
    const flushed = flushDirtyAccounts();
    log(`Logged off ${running.length} bots, flushed ${flushed} accounts.`, "SYSTEM");

    io.close();
    server.close(() => process.exit(0));
    // steam-user's logoff handshake needs a moment; don't wait forever for it.
    setTimeout(() => process.exit(0), 8000).unref();
}
process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));